### ISSUE TITLE
Deterministic color mapping

### ISSUE THREAD

**Issue by boragokbakan** [stephane-caron/foxplot#6]
It is a minor inconvenience when I plot the same fields in two different log files (e.g. when I run the same experiment with different conditions) and get different color mappings. The color mapping is random now and different every time.

It should be very easy to get a consistent mapping using ordered sets (As Python sets are not ordered by default): https://github.com/stephane-caron/foxplot/blob/2ffdb2def70c00f950f3fcb297b75a91143b8e2c/foxplot/generate_html.py#L89

Although the inconvenience is minor, the fix is very easy as well. Do you think it's a desirable property? If so, I'll create a PR.

**Comment by stephane-caron** [comment]
Sure, feel free to open a PR :+1:
